import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.js'],
    // e2e гоняется только вне coverage — subprocess всё равно не инструментируется,
    // а с v8-coverage e2e сильно тормозит (scan --dry упирается в timeout).
    exclude: process.env.VITEST_COVERAGE ? ['tests/e2e/**'] : [],
    environment: 'node',
    globals: true,
    testTimeout: 40000,
    hookTimeout: 40000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      // cli.js НЕ включён — out-of-process (см. README)
      include: [
        'agent/schemas.js',
        'agent/config-loader.js',
        'bot.js',
        'agent/refresh-tokens.js',
        'agent/telegram-api.js',
        'agent/telegram-ingest.js',
        'agent/telegram-sessions.js',
        'agent/image-variation.js',
        'agent/health.js',
        'agent/locations.js',
        'agent/planner.js',
        'agent/matcher.js',
        'agent/hashtags.js',
        'agent/usage.js',
        'agent/queue.js',
        'agent/queue-json.js',
        'agent/queue-migrate.js',
        'agent/queue-sqlite.js',
        'agent/telegram.js',
        'agent/vision-cache.js',
        'agent/caption.js',
        'agent/vision.js',
        'agent/publishers/instagram.js',
        'agent/scanner.js',
        'agent/sources/downloader.js',
        'agent/sources/pinterest.js',
        'agent/sources/pinterest-city.js',
        'agent/sources/instagram-graph.js',
        'agent/sources/index.js',
      ],
      exclude: ['**/node_modules/**', 'tests/**'],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 50,
        statements: 70,
      },
    },
  },
});
